---
# Example execution: ansible-playbook main.yml --ask-become-pass  --limit `hostname` -i inventory.yml
- hosts: home
  connection: local
  roles:
    - { role: aptupgrade }
    - { role: cmdline }
    - { role: devtools }
    - { role: docker, tags: ['docker'] }
    - { role: mega.nz }
    - { role: restic }
- hosts: laptop
  connection: local
  roles:
    - { role: productivity }
    - { role: gnome3 }
    - { role: google-chrome }
    - { role: fonts }
    - { role: nfs-client }
    - { role: terminal-profiles }
    - { role: firefox }
    - { role: skype }
    - { role: signal }
    - { role: spotify }
    - { role: zoom }
    - { role: ec }
    - { role: r-lang }
- hosts: base
  connection: local
  roles:
    - { role: http-proxy }
