---
# Example execution: ansible-playbook main.yml --ask-become-pass  --limit `hostname` -i inventory.yml
- hosts: laptop
  connection: local
  roles:
    - { role: aptupgrade }
    - { role: gnome3 }
    - { role: devtools }
    - { role: productivity }
    - { role: docker, tags: ['docker'] }
    - { role: iancleary.jetbrains_mono }
    - { role: google-chrome }
    - { role: fonts }
    - { role: cmdline }
    - { role: nfs-client }
    - { role: mega.nz }
    - { role: terminal-profiles }
    - { role: firefox }
    - { role: ec }

