---
- name: Update apt-get repo and cache
  become: yes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install nfs-client packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-common 

- name: Share mount
  become: yes
  blockinfile:
    path: /etc/fstab
    create: yes
    marker: "# {mark} Mounting share"
    block: |
      {{ item }}
  with_items: "{{ share_mount }}"
